GraspDetectorGPD:
  ros__parameters:
    cloud_topic: /camera/depth_registered/points
    rviz: true
    device: 0
    auto_mode: false
GraspPlanner:
  ros__parameters:
    grasp_service_timeout: 8
    grasp_score_threshold: 0
