GraspDetectorGPD:
  ros__parameters:
    cloud_topic: /camera/pointcloud
    # cloud_topic: "/camera/aligned_depth_to_color/color/points"
    rviz: true
    device: 1 # 0:CPU, 1:GPU, 2:VPU
    auto_mode: true
    plane_remove: true
    object_detect: false
    # grasp workspace in camera frames
    workspace: [0.0, 1.0, -0.35, 0.35, -0.1, 1.0]
    # gripper geometry parameters in metre
    # finger_width: the finger thickness
    # hand_outer_diameter: the maximum robot hand aperture 
    # hand_depth: the hand depth (the finger length)
    # hand_height: the finger breadth
    finger_width: 0.005
    hand_outer_diameter: 0.100
    hand_depth: 0.038
    hand_height: 0.020
GraspPlanner:
  ros__parameters:
    grasp_score_threshold: 1
    grasp_frame_id: "base"
    grasp_approach: [0.0, 0.0, -1.0] # expect approaching in -z axis
    grasp_approach_angle: 0.523 # 1.047=PI/3 # 0.785=PI/4 # 0.523=PI/6 # 0.345=PI/9 # acceptable approaching angle
    grasp_offset: [-0.030, -0.000, 0.000]
    # grasp boundry in grasp_frame_id
    grasp_boundry: [-0.35, 0.35, -0.7, -0.35, -0.15, 0.15]
    eef_offset: 0.174
    eef_yaw_offset: -0.7854 # M_PI/4
    finger_joint_names: ["panda_finger_joint1", "panda_finger_joint2"]
