GraspDetectorGPD:
  ros__parameters:
    cloud_topic: /camera/pointcloud
    rviz: false
    device: 0
    auto_mode: false
GraspPlanner:
  ros__parameters:
    grasp_score_threshold: 0
    grasp_frame_id: "camera_color_optical_frame"
